### PR TITLE
CI Enhancements

### LINKED ISSUE #31: Build wheels for PyPi
Allow wheels to be built for PyPI for faster installation.

### LINKED ISSUE #32: Add pre-commit
Add `pre-commit` so things like `black` and `pylint` can be pinned to specific versions.

### PR DESCRIPTION
**Pull request by tekktrik**
Fixes #31
Fixes #32

- Uses the same composite actions for building and PyPI releases as the CircuitPython libraries.  I think this is fine since none of steps there are library-specific, but another option to use the steps directly so any such changes there don't propagate here in the future.
- Adds `pre-commit`
- Adds REUSE, so lots of new licenses, most of which I attributed to you @makermelissa
- Now builds and uploads pure Python wheels to PyPI as a result of the CI changes
- Some reformatting and linting due to pinning specific versions of `pylint` and `black`, as well as other pre-commit hooks potentially

### CODE REVIEW

**Comment by tekktrik** [comment]
@makermelissa is this okay or should I not use the composite actions?

**Comment by tekktrik** [comment]
I think it actually makes more sense not to use the composite actions since I have some changes in mind that wouldn't be compatible with Blinka libraries

**Comment by makermelissa** [comment]
Hey, sorry I missed being tagged in this one @tekktrik. I'm not sure what you mean by composite actions. I think you can make whatever changes you need to as long as users are still able to install via PIP.

**Comment by tekktrik** [comment]
I've marked this on my list of things to address, hoping to address in a different fashion this week.

**Pull request closed without merging**
