### PR TITLE
allow multibyte write-then-read 

### PR DESCRIPTION
**Pull request by ladyada**
is backcompatible if you pass in a byte instead of a bytearray

### CODE REVIEW

**Comment by ladyada** [comment]
should 'just work' with any existing driver!

**Comment by caternuson** [comment]
What's a good driver to test this with?

**Comment by makermelissa** [comment]
@caternuson, it looks like a couple good ones to test that would use this are:
https://github.com/adafruit/Adafruit_CircuitPython_ADT7410
and https://github.com/adafruit/Adafruit_CircuitPython_FRAM (using I2C)

**Comment by ladyada** [comment]
any o these :)
https://github.com/search?q=org%3Aadafruit+write_then_readinto&type=Code

**Comment by makermelissa** [comment]
Oooh, neat little trick!

**Comment by caternuson** [comment]
That is a neat search trick!

There's still this check being done in Blinka:
<https://github.com/adafruit/Adafruit_Blinka/blob/c12a47fcd81c7d89dea171551cb81b25d2b935a1/src/adafruit_blinka/microcontroller/generic_linux/i2c.py#L62>
Wasn't that a kernel driver limitation?

**Comment by ladyada** [comment]
yeah that PR is coming next

**Review by makermelissa — APPROVED** [review]
Tested successfully with ADT7410. Code changes look good to me.

**Comment by makermelissa** [comment]
I'll go ahead and bump this.

**Comment by caternuson** [comment]
how'd you get around the blinka check?

**Comment by makermelissa** [comment]
Most likely the ADT7410 only used a single byte, so it didn't trip it. I think the main test here was really to check that it didn't break existing drivers as I don't believe the multibyte commands had been implemented yet.

**Comment by ladyada** [comment]
this update is back compatible - and blinka doesnt support multi-byte addresses (yet) so ya wouldnt bump into it :)

**Comment by caternuson** [comment]
ah, so the test was just for the backwards compat? ok. i was looking to test the actual multi byte, so was waiting for that.

**Comment by ladyada** [comment]
will submit a PR later tonite! the branch is still on my Pi :D

**Pull request merged**
